// <auto-generated />
using System;
using ConsoleApp1.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsoleApp1.Migrations
{
    [DbContext(typeof(GoodsContext))]
    partial class GoodsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("ConsoleApp1.DB.Category", b =>
                {
                    b.Property<Guid>("IdCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdCategory");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            IdCategory = new Guid("dbd53a84-3706-4b89-a135-da888aa024a7"),
                            Name = "Овощи"
                        },
                        new
                        {
                            IdCategory = new Guid("7b7e52a3-9362-4631-8c01-d8577a0d7f62"),
                            Name = "Фрукты"
                        });
                });

            modelBuilder.Entity("ConsoleApp1.DB.Good", b =>
                {
                    b.Property<Guid>("IdGood")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CategoryIdCategory")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<double>("Sale")
                        .HasColumnType("REAL");

                    b.HasKey("IdGood");

                    b.HasIndex("CategoryIdCategory");

                    b.ToTable("Goods");
                });

            modelBuilder.Entity("ConsoleApp1.DB.Good", b =>
                {
                    b.HasOne("ConsoleApp1.DB.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryIdCategory");

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
